package.json

The `files` entry in the `package.json` was incorrect when publishing
because that file is copied to the `lib` directory prior to publishing.
Instead of referring to `lib/**/*`, the `files` entry should just be
`*`.

[publish] Fix the package contents.

---

.github/workflows/release.yml

Also removing the tag `latest` argument.

Re-enable examples in release

---

.github/workflows/main.yml

Avoid build failures on main e.g.: https://github.com/pulumi/pulumi-cdk/runs/6650009887?check_suite_focus=true

Publish from main only if version bump occurs

---

examples/ecscluster/Pulumi.yaml
examples/ecscluster/index.ts
examples/ecscluster/package.json
examples/ecscluster/tsconfig.json
examples/examples_nodejs_test.go
src/stack.ts

Enables passing stack properties to the underlying CDK stack.
This is particularly useful for specifying `region` and `account` env variables.
These are needed for non-"environment agnostic" stacks to function correctly.
Fixes #47.
Fixes #48.

Support specifying stack properties

---

.github/workflows/main.yml
.github/workflows/release.yml
.github/workflows/run-acceptance-tests.yml
examples/api-websocket-lambda-dynamodb/index.ts
examples/examples_test.go
examples/fargate/index.ts
examples/fargate/package.json

Using LTS versions.
A dependency updated to require Node 16 awhile ago which broke our tests.  https://github.com/aws/constructs/pull/1682
Use newer `aws-native` version in a test.
Fix up networking configuration in fargate test.
Fixes #81.

Bump CI to Node 18

---

examples/examples_nodejs_test.go

As per, https://github.com/pulumi/pulumi-aws-native/issues/1186 we're seeing intermittent errors in the creation of `aws-native:ec2:SubnetRouteTableAssociation` This change enables retries for the affected tests to reduce the noise until we have an upstream fix 
Fixes https://github.com/pulumi/pulumi-cdk/issues/96

Retry flakey integration tests

---

.github/actions/build/action.yml
.github/actions/lint/action.yml
.github/workflows/main.yml
.github/workflows/release.yml
.github/workflows/run-acceptance-tests.yml
.npmignore
examples/alb/index.ts
examples/alb/package.json
examples/api-websocket-lambda-dynamodb/package.json
examples/apprunner/package.json
examples/appsvc/package.json
examples/cron-lambda/index.ts
examples/cron-lambda/package.json
examples/ec2-instance/package.json
examples/ecscluster/package.json
examples/fargate/package.json
examples/s3-object-lambda/index.ts
examples/s3-object-lambda/package.json
examples/s3-object-lambda/src/s3-object-lambda-stack.ts
package.json
yarn.lock

This PR updates the workflows and scripts
**Workflows**
- Splits the acceptance tests to run in parallel across 3 workers
- Runs unit tests and acceptance tests in different jobs
- Applies the same changes to the release workflow
- Moves some reusable logic into actions/*/action.yml files
**Others**
- Replaced the `package.json` `files` config with `.npmignore`
- Instead of running npm publish from the `lib` directory, it is now run
from the root directory (this is in preparation of #147 which needs
non-lib files included)
- Separated out a `prepare` script from `build` so that build can be run
locally without updating the `package.json` version field
- Added a `watch` and a `test:watch` script
- run `yarn link` from the root of the directory instead of `lib`
- This also requires us to …

chore: update workflows and scripts

---

.github/workflows/main.yml
.github/workflows/release.yml

There were some leftovers from refactoring done in #148. `yarn run prepare` should be `yarn run set-version` instead
Fixes #150

Fix references to 'yarn run prepare'

---

examples/examples_nodejs_test.go
examples/go.mod
examples/go.sum

Unfortunately the websocket test is too flaky and has been failing
frequently (#157, #155). Removing the piece that validates the dynamodb
record exists in the table since that is the part that is too flaky.
fixes #157

chore: remove flaky websocket test

---

examples/alb/package.json
examples/api-websocket-lambda-dynamodb/package.json
examples/apprunner/package.json
examples/appsvc/index.ts
examples/appsvc/package.json
examples/cloudfront-lambda-urls/Pulumi.yaml
examples/cloudfront-lambda-urls/index.handler.ts
examples/cloudfront-lambda-urls/index.ts
examples/cloudfront-lambda-urls/package.json
examples/cloudfront-lambda-urls/tsconfig.json
examples/cron-lambda/package.json
examples/ec2-instance/package.json
examples/ecscluster/package.json
examples/examples_nodejs_test.go
examples/fargate/package.json
examples/s3-object-lambda/package.json
package.json
yarn.lock

This adds tests for some additional popular resources.
aws-native:s3:Bucket
aws-native:s3:BucketPolicy
aws-native:cloudfront:KeyValueStore
aws-native:cloudfront:Function
aws-native:lambda:Function
aws-native:iam:Role
aws-native:lambda:Permission
aws-native:lambda:Alias
aws-native:lambda:Url
aws-native:lambda:Version
aws-native:cloudfront:Distribution
aws-native:cloudfront:CloudFrontOriginAccessIdentity

chore: adding tests for cloudfront and lambda

---

.gitignore
examples/eventbridge-sns/Pulumi.yaml
examples/eventbridge-sns/index.handler.ts
examples/eventbridge-sns/index.ts
examples/eventbridge-sns/package.json
examples/eventbridge-sns/tsconfig.json
examples/examples_nodejs_test.go
src/aws-resource-mappings.ts
src/cfn-resource-mappings.ts
src/converters/app-converter.ts
src/pulumi-metadata.ts
src/types.ts
tests/aws-resource-mappings.test.ts

Adds tests for additional resources and adds mappings for very common
resources that do not yet have CCAPI support.
- AWS::SQS::QueuePolicy
- AWS::SNS::TopicPolicy
```
aws-native:sns:Subscription
aws-native:sqs:Queue
aws-native:sns:Topic
aws-native:sns:Subscription
aws-native:iam:Role
aws-native:lambda:Function
aws-native:events:EventBus
aws-native:events:Rule
aws-native:sns:Topic
```

Add another example and map additional resources

---

src/pulumi-metadata.ts
tests/interop.test.ts
tests/pulumi-metadata.test.ts

Some resources properties are an object type with additionalProperties.
These properties should not have their keys transformed, but should have
their values.

Fix property normalization for properties with `additionalProperties`

---

.gitignore

So that contributors can customize direnv and Emacs settings without checking them into the repository accidentally.

Ignore direnv and Emacs files

---

src/interop.ts

Before this change, logging could generate "not supported" errors in the stream.
I1104 14:23:22.081768   66128 eventsink.go:59] CfnResource aws-native:ec2:SubnetRouteTableAssociation:
{"routeTableId":"Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value
or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee
https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of
@pulumi/pulumi.","subnetId":"Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a
JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v =>
JSON.stringify(v))\n\nSee …

Fixes debug logging of CfnResource

---

integration/ec2/Pulumi.yaml
integration/ec2/index.ts
integration/ec2/package.json
integration/ec2/tsconfig.json
integration/examples_nodejs_test.go
package.json
src/converters/app-converter.ts
src/graph.ts
tests/converters/app-converter.test.ts
tests/graph.test.ts
yarn.lock

Depends on https://github.com/pulumi/pulumi-aws-native/pull/1797
Because of https://github.com/pulumi/pulumi-aws-native/issues/1798 we need to add a special case for Ipv6 cidr blocks that are added to the VPC via a `VPCCidrBlock` resource.
This PR adds special handling where we track both the `Vpc` and the `VpcCidrBlock` resource and swap any references.

Fix IPV6 cidr blocks

---

integration/examples_nodejs_test.go
integration/route53/Pulumi.yaml
integration/route53/index.ts
integration/route53/package.json
integration/route53/tsconfig.json
src/aws-resource-mappings.ts
tests/aws-resource-mappings.test.ts
tests/cdk-resource.test.ts

This PR adds support for Route53 records (`AWS::Route53::RecordSet`) which is not currently supported by CCAPI.
I've also added integration tests for the Route53 constructs.
re #183, closes #177

Add support for Route53 records

---

integration/examples_nodejs_test.go
integration/secretsmanager/Pulumi.yaml
integration/secretsmanager/index.ts
integration/secretsmanager/package.json
integration/secretsmanager/tsconfig.json
package.json
src/converters/app-converter.ts
src/converters/secrets-manager-dynamic.ts
tests/converters/app-converter.test.ts
tests/converters/secretsmanager-converter.test.ts
tests/mocks.ts
yarn.lock

CloudFormation has a capability that allows you to dynamically resolve secretsmanager values at deploy time.
This PR adds special handling for these values by mapping them to the `getSecretVersion` function. I can think of two ways that these values would end up being referenced in a CDK application
1. The user provides a string value for the secretId and the reference is a complete string.
2. The user provides a reference value for the secretId and the reference is a Fn::Join intrinsic
There may be other cases, but if there are I think they are not very common and we can handle them if users create issues.
re #183, fixes #199

Handle SecretsManager dynamic references

---

integration/examples_nodejs_test.go
integration/misc-services/Pulumi.yaml
integration/misc-services/index.ts
integration/misc-services/package.json
integration/misc-services/tsconfig.json
package.json
src/aws-resource-mappings.ts
src/cfn-resource-mappings.ts
tests/aws-resource-mappings.test.ts
tests/cdk-resource.test.ts
tests/cfn-resource-mappings.test.ts
tests/mocks.ts
yarn.lock

This adds integration tests for the remaining construct libraries.
Also adds mapping for one missing CCAPI resource
(`AWS::Events::EventBusPolicy`)
closes #183

Add integration tests for remaining resources

---

integration/examples_nodejs_test.go
integration/replace-on-changes/Pulumi.yaml
integration/replace-on-changes/index.ts
integration/replace-on-changes/package.json
integration/replace-on-changes/step2/index.ts
integration/replace-on-changes/tsconfig.json
src/cfn-resource-mappings.ts
src/interop.ts
src/naming.ts
tests/cfn-resource-mappings.test.ts
tests/converters/app-converter.test.ts
tests/utils.ts

This PR updates our mapping to create resources using the SDK directly
instead of creating a `pulumi.CustomResource`. By using a
`pulumi.CustomResource` we were missing out on all the resource specific
things from the generated SDK. (`replaceOnChanges`, required property
validation, etc).
closes #216

Create aws ccapi resources by using the SDK

---

integration/examples_nodejs_test.go
integration/replace-on-changes/index.ts
integration/replace-on-changes/step2/index.ts
src/cdk-logical-id.ts
src/stack.ts
tests/cdk-resource.test.ts

CDK automatically adds a hash suffix to the resource logicalId (which we
then use as the Pulumi Resource name). When pulumi autonaming takes
place we then append an additional random suffix so we end up with names
like `testapimyapiCloudWatchRoleA84BAE8E-120b18f`. Apart from this
looking bad it also takes up 16 characters for each name and increases
the likelihood of running into naming limits.
This PR overrides the `allocateLogicalId` method on the `cdk.Stack`.
Most of the code is simply forked from the CDK implementation with the
removal of the piece that generates the hash.
You can view the CDK version here
https://github.com/aws/aws-cdk/blob/ccab485b87a7090ddf0773508d7b8ee84ff654b0/packages/aws-cdk-lib/core/lib/stack.ts?plain=1#L1357
closes #185

Remove CDK generated hash suffix on resource names

---

integration/apigateway/index.ts
integration/apigateway/sfn-api.ts
integration/custom-resource/index.ts
integration/examples_nodejs_test.go
integration/misc-services/index.ts
src/assembly/stack.ts
src/cfn.ts
src/converters/app-converter.ts
tests/converters/app-converter.test.ts
tests/graph.test.ts
tests/utils.ts

This adds support for the CloudFormation `Fn::FindInMap` intrinsic
function.
Docs on the `Mappings` section of a CloudFormation template can be found
[here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html).
Docs on the `Fn::FindInMap` function can be found [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-findinmap.html)
closes #187

Add support for Fn::FindInMap intrinsic

---

schemas/README.md

Adds a README explaining where the aws-native schema is from, how it is used, and what the grammar is. This is internal documentation targeting contributors.

Add schemas readme

---

src/interop.ts
src/pulumi-metadata.ts
tests/interop.test.ts

`pulumi.Output` values seem to be able to reach the `normalize` step of translating properties from a CDK notation to a Pulumi notation and making sure the casing is right. This may be happening in particular because CF intrinsic evaluator may emit Output values. With the fix, the `normalize` step can deeply recur into these eventual values and make sure that the property casing is correctly handled regardless of whether a value is an eventual or not.
This seems to resolve an issue I have been running into when testing a Kinesis Stream.

Handle pulumi.Output recursively when translating CDK properties to Pulumi

---

.eslintrc.js
src/converters/app-converter.ts

A combination of fixes and relaxed linter rules, `yarn run lint` now passes without warnings.

chore: fix all lint warnings

---

README.md
examples/alb/index.ts
integration/apigateway/sfn-api.ts
integration/examples_nodejs_test.go
src/cfn-resource-mappings.ts
src/stack.ts
tests/basic.test.ts
tests/cdk-resource.test.ts
tests/mocks.ts
tests/synthesizer.test.ts

This PR enables the aws-native `AutoNaming.autoTrim` feature by default.
It does this by creating an aws-native provider by default if the user
does not provide one.
I've updated tests to remove the workarounds.
**Alternatives**
1. We could require that the user configure this themselves.
2. Is there a way to set config values programatically?
closes #62, closes #70

Enable `autoTrim` behavior by default

---

integration/examples_nodejs_test.go
integration/kinesis/Pulumi.yaml
integration/kinesis/index.ts
integration/kinesis/package.json
integration/kinesis/tsconfig.json
package.json
src/assembly/stack.ts
src/cfn.ts
src/converters/app-converter.ts
src/converters/intrinsics.ts
tests/converters/intrinsics.test.ts

Support [Condition Functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html).
Fixes https://github.com/pulumi/pulumi-cdk/issues/206
With this change, if CDK emits CF templates with Condition Functions, pulumi-cdk evaluates these. This unlocks support for new constructs such as the Kinesis Stream construct.

Support Condition Functions

---

README.md
api-docs/Namespace.interop.md
api-docs/Namespace.synthesizer.md
api-docs/README.md
examples/scalable-webhook/lambda-fns/publish/lambda.ts
examples/scalable-webhook/lambda-fns/subscribe/lambda.ts
examples/the-big-fan/lambda-fns/subscribe/anyOtherStatus.ts
examples/the-big-fan/lambda-fns/subscribe/createdStatus.ts
package.json
src/custom-resource-mapping.ts
src/graph.ts
src/index.ts
src/interop.ts
src/pulumi-metadata.ts
src/stack.ts
src/synthesizer.ts
typedoc.json
yarn.lock

This PR introduces a new tool [typedoc](https://typedoc.org/) which automatically generates API docs from TypeScript code. I think this is easier than having to remember to manually update the API documentation. It also forces us to add code comments to document the API.
I've also added a couple of scripts to the `build` script to ensure we run `docs`, `format`, && `lint` as part of `build`.

chore: add api-docs auto generation

---

.github/actions/build/action.yml
api-docs/Namespace.interop.md
api-docs/Namespace.synthesizer.md
api-docs/README.md
src/converters/app-converter.ts
src/converters/intrinsics.ts
typedoc.json

Now that we run `docs`, `format`, & `lint` we should also ensure that we fail the build if there are any changes.

chore: add check worktree clean to build

---

integration/cloudfront/index.ts
integration/kinesis/index.ts
integration/logs/index.ts

The Kinesis Stream construct has a default policy of `Retain`. Switching to `Destroy` so the tests clean up after themselves

chore: add removal policy to kinesis stream

---

src/cfn.ts
src/converters/app-converter.ts
src/converters/intrinsics.ts
src/output-map.ts
src/pulumi-metadata.ts
tests/converters/intrinsics.test.ts

This change adds some tests and comments around the `Ref` intrinsic implementation and moves it to `intrinsics.ts`. The one change in behavior is that now `Ref` is able to consult Pulumi metadata from the `aws-native` provider. The metadata helps it resolve to the same values as it would in CloudFormation for resources that have non-standard `Ref` behavior.  The correctness of this process is up to the correctness of the metadata tables. Entries not found in the metadata tables default to using Pulumi `id` for most cases should do the right thing.
Fixes https://github.com/pulumi/pulumi-cdk/issues/173
Needs https://github.com/pulumi/pulumi-aws-native/pull/1836

Improve the Ref intrinsic implementation

---

README.md
api-docs/README.md
examples/examples_nodejs_test.go
examples/lookups-enabled/index.ts
examples/stack-provider/Pulumi.yaml
examples/stack-provider/index.ts
examples/stack-provider/package.json
examples/stack-provider/tsconfig.json
src/converters/app-converter.ts
src/converters/artifact-converter.ts
src/stack.ts
src/types.ts
tests/basic.test.ts
tests/cdk-resource.test.ts
tests/mocks.ts
tests/options.test.ts

It has been possible to specify Pulumi resource options at the stack level, but it did not flow through to the actual resources. This PR makes sure that the inheritance works correctly.
This PR also adds functionality to automatically set the Stack environment based on the App provider. Because the App creates the stacks in an async context, we can use provider functions to lookup the environment and then pass the resolved environment to the stack. 
For now this is something that the user will have to specify (example in the `lookups` example test). This would mean that all Stacks have their environment provided by default. This will cut down on the number of Intrinsics used in the generated template. The reason I am not turning this on by default is because it requires lookups to be …

Add ability to specify resource options at the stack level

---

api-docs/Namespace.synthesizer.md
examples/s3-object-lambda/src/s3-object-lambda-stack.ts
src/converters/app-converter.ts
src/synthesizer.ts
tests/mocks.ts
tests/synthesizer.test.ts

Previously we were generating a physical name for the staging resources (S3 Bucket / ECR Repository) because it was mistakenly assumed that we needed those to be known values for CDK to work. Turns out that we can use `asString` on the Output values and CDK handles it correctly. So this PR does a couple of things:
1. Removes the hard coded resource names and allows Pulumi to generate an autoname.
2. Removes the dependency each stack had on the staging stack. Because we are using Output values to reference the assets, each resource can depend on the individual asset directly. This allows for more resources to be provisioned in parallel. On the `eventbridge-sns` test this had a 20% decrease in deployment time.

Reference assets directly

---

.github/workflows/upgrade-aws-native.yml
integration/kinesis/package.json
integration/removal-policy/package.json
integration/removal-policy/step2/package.json
package.json
scripts/update-aws-native.sh
yarn.lock

This PR adds a workflow that automates updating the @pulumi/aws-native dependency. This one is a special case because the metadata.json file also needs to be updated.
fixes #149

chore: add workflow to upgrade @pulumi/aws-native workflow

---

src/aws-resource-mappings.ts
src/converters/intrinsics.ts
tests/converters/intrinsics.test.ts

We use the `Ref` metadata to determine which attribute the `Ref` intrinsic should reference. This metadata is only valid for CCAPI resources though so we need to exclude any other resource type.
This PR checks the internal `__pulumiType` to determine if the resource is an `aws-native` resource. I chose to do it this way because we need to check the resource itself, we can't rely on any other information source. For example, the user could provide their own mapping function that maps some resources to `aws-native` and some resources to `aws`.
closes #262

Do not use Ref metadata for AWS Provider resources

---

examples/examples_nodejs_test.go
examples/lookup-azs/Pulumi.yaml
examples/lookup-azs/index.ts
examples/lookup-azs/package.json
examples/lookup-azs/tsconfig.json

If you provide an explicit environment to the stack (there are a lot of
reasons to do this) then you have to enable lookups in order for the
stack to lookup the availability zones.
It would be nice if you could just use Pulumi functions to lookup the
AZs and provide that, but the values have to be strings (can't be
promises/outputs). An easy workaround for this is to use the `getAzs`
intrinsic to defer the lookup and allow the intrinsic to be converted to
a Pulumi function.
I am adding an example of how to do this. The reason we don't want to do
this by default is that the number of availability zones is not
something that should every change without the user knowing about it.
CDK handles that by having the lookup store the value in the
`cdk.context.json` file so the lookup is never …

chore: add example of looking up availability zones

---

Makefile
renovate.json5
scripts/update-aws-native.sh

This adds a [postUpgradeTask](https://github.com/pulumi/renovate-config?tab=readme-ov-file#post-upgrade-tasks) to update metadata whenever `@pulumi/aws-native` is bumped. 
The metadata bump is straightforward enough that we should be able to run it inside Renovate without trouble.
This is defined as a make target because Renovate requires post-run tasks to be explicitly allowed, and for the moment we allow `make renovate` for simplicity. We can think about expanding allowable commands in the future.

Add a postUpgradeTask to bump metadata for aws-native

---

examples/examples_nodejs_test.go
src/synthesizer.ts

This fixes the issue by switching to use Pulumi assets instead of the filepath directly. The filepath includes the random `cdk.out` directory so it will always be different. Assets handle this case.
fixes #73

Fix BucketObjectv2 should only trigger an update on code changes

---

.npmignore

We don't need to publish these as part of the npm artifact.

chore: add additional directories to npmignore

---

src/assembly/manifest.ts
src/assembly/stack.ts
src/assembly/types.ts
src/cfn.ts
src/converters/app-converter.ts
src/converters/intrinsics.ts
src/graph.ts
src/interop.ts
src/stack-map.ts
src/stack.ts
tests/assembly/manifest.test.ts
tests/assembly/stack.test.ts
tests/converters/app-converter.test.ts
tests/converters/intrinsics.test.ts
tests/converters/secretsmanager-converter.test.ts
tests/converters/ssm-converter.test.ts
tests/graph.test.ts
tests/mocks.ts
tests/options.test.ts
tests/stack-map.test.ts
tests/test-data/custom-resource-stack/stack-manifest.json
tests/test-data/nested-stack/manifest.json
tests/test-data/nested-stack/stack-manifest.json
tests/test-data/nested-stack/teststack.assets.json
tests/test-data/nested-stack/teststack.template.json
tests/test-data/nested-stack/teststacknesty613E34DC.nested.template.json
tests/test-data/nested-stack/tree.json
tests/utils.ts

This change adds support for Nested Stacks to `pulumi-cdk`.
In CDK, a nested stack is a CDK stack that you create inside another stack, known as the parent stack. Users create nested stacks using the [NestedStack](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.NestedStack.html) construct.
By using nested stacks, users can organize resources across multiple stacks. Nested stacks also offer a way around the AWS CloudFormation 500-resource limit for stacks. A nested stack counts as only one resource in the stack that contains it. However, it can contain up to 500 resources, including additional nested stacks.
While Pulumi doesn't have those limitations, many existing CDK constructs use nested stacks to get around the CloudFormation limitations. The EKS cluster construct is one of …

Enhance CDK support with nested stack handling

---

.github/workflows/release.yml

We were creating the tag, but not creating a GitHub release.

chore: add github release to release workflow

---

.github/workflows/main.yml
.github/workflows/release.yml

This adds a concurrency group to the release workflow so only 1 release
will occur at a time
fixes #284

chore: add concurrency group to release job

---

api-docs/Namespace.interop.md
api-docs/README.md
src/converters/app-converter.ts
src/converters/intrinsics.ts
src/internal/interop.ts
src/interop.ts
src/output-map.ts
src/pulumi-metadata.ts
src/stack-map.ts
src/stack.ts
src/synthesizer.ts
src/types.ts
tests/converters/app-converter.test.ts

Types only need to be marked as `@internal` if they would be exported
from the top level `index.ts` file, but you don't want them to. Marking
something as `@internal` means they are stripped from the compiled type
files and this causes type errors because some files will try to
reference types that do not exist anymore.
Example error when running `tsc` in a project where `@pulumi/cdk` is
installed.
```
node_modules/@pulumi/cdk/lib/converters/app-converter.d.ts:6:10 - error TS2305: Module '"../interop"' has no exported member 'CdkConstruct'.
6 import { CdkConstruct } from '../interop';
~~~~~~~~~~~~
```
I've unmarked things as `@internal` that are not exported and moved some
things to a new `interna/interop.ts` file that were in an exported file.
Now that they are not in an exported file we …

Types incorrectly marked as @internal

---

renovate.json5

Renovate can't handle the alpha versioning scheme used by `@aws-cdk-cli-lib-alpha`
When given `^2.178.1-alpha.0` it reads the `-alpha.0` as a `prerelease`
which means it marks the update as "unstable". For "unstable" updates
renovate only recognizes bumps to the `prerelease` portion, so it would
recognize `2.178.1-alpha.2`, but not `2.179.0-alpha.0`.
(it expects major.minor.patch to always be the same)
To handle this, we tell renovate how to read the versioning. The important part
is that we switch the `-alpha.0` to be read as the `compatibility` part instead of `prerelease`
see https://docs.renovatebot.com/modules/versioning/regex/

Fix renovate config to recognize @aws-cdk/cli-lib-alpha versions

---

examples/examples_nodejs_test.go
renovate.json5

The renovate regex was not quite correct as it was missing the `^` in
the version string.
see regexr.com/8che4
Also just disabling the test causing since I'm running into that pretty frequently #277
re #277

Fix renovate regex

---

.github/workflows/acceptance-tests.yml

This switches the AWS Access from hardcoded access keys that are pulled
from GitHub secrets to use Pulumi ESC environments.
re #3731

Switch AWS access to use ESC

---

renovate.json5

Follow up to #345 which was supposed to automate the CDK upstream
updates, but did not. The previous PRs only enabled us to manually
trigger the upgrades. This PR sets `dependencyDashboardApproval: false`
which is required for renovate to automatically create the PR when there
are version bumps.
This also adds the `aws-cdk-lib` dependency to the cdk group so that the
cdk dependencies are upgraded together.

Automate renovate updates for CDK dependencies

---

.github/workflows/command-dispatch.yml
.github/workflows/main.yml
.github/workflows/release.yml
.github/workflows/run-acceptance-tests.yml

These changes migrate this repo's GitHub Actions Workflows to use ESC secrets instead of GitHub Secrets.
The changes are largely mechanical:
- Common configuration for all ESC actions within a workflow is added to the workflow's environment variables
- Permissions are expanded as necessary for workflows that do not grant `id-token: write` permissions
- `read-all` permissions are replaced with the union of all explicit read permissions and `id-token: write`
- Default permissions are replaced with `write-all`, which is the equivalent of all explicit write permissions and
`id-token: write`
- Explicit permissions are modified to grant `id-token: write`
- A step that fetches ESC secrets and populates environment variables is added to each step that reads secrets
- Direct references to secrets …

Use ESC secrets
